In [ ]:
from google.colab import drive
drive.mount('/content/drive')
"""
Esto es para usar tu cuenta de drive, esto es personal para cada uno por lo que
no se expondra informacion personal. Deberas darle permisos a Colab para acceder
a tu google drive

Para que se ejecute bien, debes crear en tu drive las siguientes carpetas en tu
drive: Hitos_Skillnest, dentro de ella crear la carpeta Hito1 y colocar dentro
el archivo de 34_SuperTienda_Espanol.db

Mas abajo dejare una opcion para ejecutarlo sin el drive.
"""

Mounted at /content/drive

'\nEsto es para usar tu cuenta de drive, esto es personal para cada uno por lo que\nno se expondra informacion personal. Deberas darle permisos a Colab para acceder\na tu google drive\n\nPara que se ejecute bien, debes crear en tu drive las siguientes carpetas en tu\ndrive: Hitos_Skillnest, dentro de ella crear la carpeta Hito1 y colocar dentro\nel archivo de 34_SuperTienda_Espanol.db\n\nMas abajo dejare una opcion para ejecutarlo sin el drive.\n'

In [ ]:
#Setting de sql y pandas
import sqlite3
import pandas as pd

%load_ext sql
%config SqlMagic.style = '_DEPRECATED_DEFAULT'

"""
Dependiendo de la opcion que uses, deberas comentar una opcion u otra para
evitar generar errores y luego cambiarlo en conn = sqlite3.connect(opcion_Elegida)
"""

#Ruta del archivo guardada en drive
ruta_drive = '/content/drive/MyDrive/Hitos_Skillnest/Hito1/34_SuperTienda_Espanol.db'

#Ruta del archivo subida al entorno, debes subirlo a la raiz del entorno de ejecucion.
#ruta = '/content/34_SuperTienda_Espanol.db'

"""
-----------------------------------------------
"""

#Cambiar la variable de ruta segun si estas usando el drive o el archivo subido
#al entorno de ejecucion
conn = sqlite3.connect(ruta_drive) #Se realiza la conexion con la base de datos


#Guardamos la consulta SQL como string, en este caso es para poder conseguir
# el nombre de las tablas presentes en la base de datos.
query = "SELECT name FROM sqlite_master WHERE type='table';"

#ejecutamos la consulta en la base de datos
df_tables =  pd.read_sql_query(query, conn)

print(df_tables) # :D tablas

The sql extension is already loaded. To reload it, use:
  %reload_ext sql
                name
0           Clientes
1          Productos
2          Geografia
3  Cliente_Ubicacion
4          Campanias
5            Pedidos
6     Detalle_Pedido
7            Soporte

In [ ]:
#Setting de los Dataframes
df_pedidos = pd.read_sql("SELECT * FROM Pedidos", conn)

Enfoque de clientes

Variables a calcular:

Cuales son los segmentos que mas pedidos realizan, Cuales son las categorias mas pedidas por cada segmento, cuales son los segmentos que producen mayor inversion, los canales preferidos mas utilizados en general, los canales preferidos mas utilizado por cada segmento, la media del puntaje de fidelidad, posible relacion entre segmentos y puntos de fidelidad.

In [ ]:
df_pedidos

,ID_Pedido,ID_Cliente,Fecha_Pedido,Fecha_Envio,Modo_Envio,ID_Campania,Estado_Pedido,Observacion_Interna
0,ORD-2023-00001,C0174,2025-03-31,2025-04-04,Estándar,None,Completado,Cliente frecuente
1,ORD-2023-00002,C0254,2024-03-25,2024-03-25,Segunda Clase,MKT005,Completado,Sin observaciones
2,ORD-2023-00003,C0203,2024-02-20,2024-02-24,Estándar,MKT001,Completado,Revisar descuento aplicado
3,ORD-2023-00004,C0258,2023-10-29,2023-10-31,Primera Clase,None,Enviado,Sin observaciones
4,ORD-2023-00005,C0118,2025-03-30,2025-04-01,Estándar,MKT006,Completado,Verificar dirección
...,...,...,...,...,...,...,...,...
1195,ORD-2025-01196,C0011,2023-12-16,2023-12-22,Primera Clase,MKT008,Completado,Escalado por soporte
1196,ORD-2025-01197,C0215,2023-12-16,2023-12-19,Mismo Día,MKT008,Completado,Verificar dirección
1197,ORD-2025-01198,C0195,2024-06-25,2024-07-01,Mismo Día,MKT007,Completado,Entrega parcial
1198,ORD-2025-01199,C0226,2024-04-12,2024-04-15,Segunda Clase,None,Completado,Sin observaciones
1199,ORD-2025-01200,C0209,2024-07-06,2024-07-11,Segunda Clase,None,Completado,Cliente frecuente

In [ ]:
df_pedidos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID_Pedido            1200 non-null   object
 1   ID_Cliente           1200 non-null   object
 2   Fecha_Pedido         1200 non-null   object
 3   Fecha_Envio          1200 non-null   object
 4   Modo_Envio           1200 non-null   object
 5   ID_Campania          516 non-null    object
 6   Estado_Pedido        1200 non-null   object
 7   Observacion_Interna  1200 non-null   object
dtypes: object(8)
memory usage: 75.1+ KB

In [ ]:
df_pedidos.isna().sum()

ID_Pedido                0
ID_Cliente               0
Fecha_Pedido             0
Fecha_Envio              0
Modo_Envio               0
ID_Campania            684
Estado_Pedido            0
Observacion_Interna      0
dtype: int64

In [ ]:
df_pedidos['ID_Campania'] = df_pedidos['ID_Campania'].fillna('Sin Registro')

In [ ]:
df_pedidos.isna().sum()

ID_Pedido              0
ID_Cliente             0
Fecha_Pedido           0
Fecha_Envio            0
Modo_Envio             0
ID_Campania            0
Estado_Pedido          0
Observacion_Interna    0
dtype: int64

In [ ]:
df_pedidos.describe()

,ID_Pedido,ID_Cliente,Fecha_Pedido,Fecha_Envio,Modo_Envio,ID_Campania,Estado_Pedido,Observacion_Interna
count,1200,1200,1200,1200,1200,1200,1200,1200
unique,1200,289,646,644,4,9,4,7
top,ORD-2025-01184,C0120,2023-05-11,2024-06-25,Estándar,Sin Registro,Completado,Revisar descuento aplicado
freq,1,12,6,7,311,684,879,199

In [ ]:
df_pedidos['ID_Campania'].value_counts()

ID_Campania
Sin Registro    684
MKT003           72
MKT001           71
MKT002           71
MKT007           70
MKT005           65
MKT006           64
MKT008           62
MKT004           41
Name: count, dtype: int64

In [ ]:
df_pedidos['ID_Campania'].value_counts()

Modo_Envio
Estándar         311
Primera Clase    310
Segunda Clase    294
Mismo Día        285
Name: count, dtype: int64

In [ ]:
df_pedidos['Estado_Pedido'].value_counts()

Estado_Pedido
Completado    879
Enviado       207
Cancelado      65
Devuelto       49
Name: count, dtype: int64

In [ ]:
df_pedidos['Observacion_Interna'].value_counts()

Observacion_Interna
Revisar descuento aplicado    199
Cliente frecuente             180
Sin observaciones             171
Entrega parcial               169
Verificar dirección           165
Posible recompra              161
Escalado por soporte          155
Name: count, dtype: int64

In [ ]:
df_pedidos['ID_Pedido'].value_counts()

ID_Pedido
ORD-2025-01184    1
ORD-2025-01183    1
ORD-2025-01182    1
ORD-2025-01181    1
ORD-2025-01180    1
                 ..
ORD-2023-00005    1
ORD-2023-00004    1
ORD-2023-00003    1
ORD-2023-00002    1
ORD-2023-00001    1
Name: count, Length: 1200, dtype: int64